language: ruby
rvm:
- 2.2.4
env:
  global:
  - GIT_EMAIL: poppy-bot-ci@inria.fr
  - GIT_NAME: poppy-bot
  - GH_USERNAME: poppy-project
  - GH_REPO: poppy-simu
  - secure: I6fBFa0A9cm6meKUcgnpHiclDtBERODkpBiaDOy7SWra9EIXTx2bLyH0XYr3+hYOc9ram/7AvvpHTxtnrou3o0vDaicSphDL/SLmLqs2UGFjet039l2wd+XRs4Xkf+ftoGH/iHXprqR/Gq63tf2kjedglED75nUap2iUNsOo9PX9nGrfCXz3+kuqlJQFCnSxzsFKPJBcLPfn3cG0vrybN43WJglmwPim28jG2XYxyR+NuXjVE/bU22B1Ak2jE1t4aEFnEFKW7gekBTcgMkwk6JgJTQ1Hyf1fivkymclKR4byUhwGqqrYGSJGkhZszM/UxuwmpmgCzd/Zwyq346xvn0tyJDjKr3hcpzX1p9t2n9tBPiSEUhE/Em0GIjjjNIaMJnLL/EEtxHK8WXQfmWloKd0Ti+ruJul/U/uwEEXrmH+UaZQwKzxU0m8L20fk8qxTYhk6zkgGt/FCv5MXodS0GzHp6+wuaLEv6hMGQM7Y4NDsV/1WI05noO6yu/0mytbRaPquZhq+ZefXGmLIJYhLK7CaP5y1wz4355k/UhETYOWgVKX9vLSHSNYG1H7TXAIAReiOPTjaLsyLag28luaZpTofZ9Ea2eArKTNh7k2qtVRaeabymGTl2iuqNIqBGt6+NNkB0lDBToMCLl49AqBVZ3t87NYOjEalWZZ3RrxofQQ=
before_script:
- chmod +x ./_script/cibuild.sh
script: "./_script/cibuild.sh"
before_deploy:
- chmod +x ./_script/cideploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: _script/cideploy.sh
sudo: false
